### ISSUE TITLE
server to use defined subprotocol?

### ISSUE THREAD

**Issue by steffkes** [logux/docs#101]
I was reading across the docs and wondering if the server is supposed to use the subprotocol that was defined in the previous step, rather than a static string? As we do with the client

defined as part of the project
https://github.com/logux/docs/blob/3e83837e5e75e7b53a190523a8f9338ed43d6c20/guide/starting/project.md#L18-L22

imported for server but afterwards not used for
https://github.com/logux/docs/blob/3e83837e5e75e7b53a190523a8f9338ed43d6c20/guide/starting/server.md#L22-L34

because the client does
https://github.com/logux/docs/blob/3e83837e5e75e7b53a190523a8f9338ed43d6c20/guide/starting/client.md#L13-L28

**Comment by ai** [comment]
Server needs subprotocol to mark actions created on this server by `server.log.add(action)` or `server.process(action)`.

Later you can work with old actions from log knowing what server on server created this action. It is useful in big production projects with many changes.

Does it answer your question? Feel free to ask extra details if needed.

**Comment by steffkes** [comment]
sorry, maybe me asking this way made the conversation go this way.

I'm mainly wondering, if the `SUBPROTOCOL` const that is imported shouldn't be used instead of the static `'1.0.0'` that is currently displayed as part of the docs. 

as in: should this be changed in the docs to show a coherent usage of the configuration.

**Comment by ai** [comment]
Got it! Yes, we should use `const`. Fixed 3a53dde
