### ISSUE TITLE
In current @logux/server version `sendBack` is not a function

### ISSUE THREAD

**Issue by mrdimidium** [logux/docs#19]
The current version of the documentation uses the `Context.prototype.sendBack` method, which is not yet implemented in the current version (`v0.4.0`). Because of this, almost all examples cannot be run.

**Comment by ai** [comment]
Yeap, it is implemented in `master`

**Comment by mrdimidium** [comment]
Yeah, I found it in the source code :) I want to say that it is insanely confusing and dig into the source code to run the first example of the readme - the most unobvious and strongly repels from the tool.

**Comment by ai** [comment]
Yeap, I will release version when I will finish docs

**Comment by ai** [comment]
Logux Server 0.5 was released
