### ISSUE TITLE
What is the formal definition of Logux?

### ISSUE THREAD

**Issue by mrdimidium** [logux/docs#3]
I found 2 formulations of "A new way of client-server conversation", "Replace AJAX-REST by Redux actions synchronization between client and server" and "Logux is a client-server communication tool", but what is the real one?

**Comment by ai** [comment]
There is no real explanation for everything 😏.

Everything must be explained depends on listener context.

But “not” definitions are mostly worse, then “yes”. So “it is not a AJAX” should not a formal definition of Logux, in my opinion.

“Logux is a client-server communication tool” is too general and doesn't show the difference if Logux with other tools.

So, if you need a formal:

> A way of communication between client and server by synchronizing Redux/Vuex actions between client and server, instead of sending requests

But again, any one formal definition will work worse than definition created for your specific case and for specific audience.
