### ISSUE TITLE
Why logux use WebSocket for transport layer?

### ISSUE THREAD

**Issue by mesilov** [logux/docs#5]
Why logux use WebSocket for transport layer?

In PHP-world we have a new thing – https://github.com/dunglas/mercure based on server-sent events. 

See article «[Using SSE Instead Of WebSockets For Unidirectional Data Flow Over HTTP/2](https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/)»

Now Symfony introduce [Mercure support](https://symfony.com/blog/symfony-gets-real-time-push-capabilities).

**Comment by ai** [comment]
1. SSE doesn’t support by Edge https://caniuse.com/#search=Server-sent%20events
2. Using different protocols to income and outcome message make the code more complicated.
3. You do not need Web Socket support from your backend to work with Logux. Logux provides your WS proxy server to convert WS events to HTTP calls. It will give you better performance on languages without good concurrency (like Ruby or PHP).
4. If you really a big fan of SSE you can use them as well. Both client and server accept `Connection` object. You can implement any communication way. Web Socket is just a default choice.

**Comment by ai** [comment]
[This article](https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/) is not really good at comparing WS and SSE.

For instance, using WSS (WS over TLS, “HTTPS” for WS) will save you from any problem with proxies.

**Comment by ai** [comment]
I will keep your issue open to remind me of creating a separated article about WS vs SSE in docs.

**Comment by ai** [comment]
Closing it for now since we have a plans to add HTTP support https://github.com/logux/logux/issues/4
