### ISSUE TITLE
How to migrate classic PHP-application with REST-API and frontend based on vue.js to modern app with optimistic UI?

### ISSUE THREAD

**Issue by mesilov** [logux/docs#6]
Now I have a "how to drow the owl" problem with current documentation with logux.
Maybe a todo list or other guide will be more helpful.

Now I have:
- LAMP stack on the backend
- REST-API for my app written on Symfony
- UI based on bootstrap and logic written on vue.js for back-office employees

In the second version of my application, I need to build a simple personal cabinet for clients with some simple features on **other** domain. 

- a personal account with a balance
- notifications from new actions (short news list)
- register form
- some QR for auth transactions

 Yes, some variations of loyalty program

I will plan to build a single PWA app and use my current REST-API, but your presentations and ideas are so sexy.

**Comment by ai** [comment]
There documentation is just started. I will cover these question in next pages

**Comment by ai** [comment]
Moved to https://github.com/logux/logux/issues/7
