### ISSUE TITLE
Logux Cloud

### ISSUE THREAD

**Issue by tomsdev** [logux/docs#67]
Hi, this is not an issue but I wanted to share this with you: there is a new kind of "on-the-edge cloud hosting" that might be very interesting for Logux servers, could make latency super low. Checkout their hacker news annoucement here: https://news.ycombinator.com/item?id=22616857

**Comment by ai** [comment]
Absolutely! Adding a new server is always hard for users and many users want some sort of server-less web sockets. For us, it will be good monetization plan.

I will start it after Logux will have its first 100 users. Right now we have around 10 production installations only.

**Comment by ai** [comment]
Moved to https://github.com/logux/logux/issues/6
