### ISSUE TITLE
Logux.io is scrolling broken on Samsung Galaxy Tab - Chrome 81.0.4044

### ISSUE THREAD

**Issue by clibu** [logux/docs#69]
On Chrome on Android in Landscape mode all the panels are shown. I can't initially scroll the left most two panels, once an item is selected from the 2nd column. Actually it's all pretty weird. Scrolling any clm scrolls them all. 

I think you can emulate in Chrome Dev Tools on your Desktop by setting a device with a responsive layout and making it wide enough. Logix.io doesn't actually respond well to resizing the device window in dev tools.

I doubt that it's an Android or Chrome issue as such.

**Comment by ai** [comment]
Thanks for the report. Fixed 1a13166
