### ISSUE TITLE
Clarification about `resend` function

### ISSUE THREAD

**Issue by nichoth** [logux/docs#94]
[This part of the docs](https://logux.org/guide/concepts/subscription/), about subscriptions, was unclear to me.

> After sending initial state, the server needs to mark all action related to this channel in resend callback. Logux will resend these actions to all clients subscribed to this channel.

What does it mean, "mark all action related to this channel"? Is there an example of what you would use the `resend` callback to do?

Thank you

**Comment by ai** [comment]
Thanks. I made text more clear ce27289

Did it help?
