### ISSUE TITLE
'preadd' event

### ISSUE THREAD

**Issue by nichoth** [logux/docs#96]
In [zero knowledge docs](https://logux.org/recipes/zero-knowledge/#zero-knowledge-server), we see

```js
server.log.type('0', (action, meta) => {
  meta.reasons.push('user:' + parseId(meta.id).userId)
}, 'preadd')
```

But that doesn't match up with the types in my installed copy. Should this be like this?

```js
server.log.type('0', (action, meta) => {
    meta.reasons.push('user:' + parseId(meta.id).userId)
}, { event: 'preadd' })
```

---

Also, I wanted to clarify, in the [docs here](https://logux.org/guide/concepts/reason/#cleaning-log-and-action-reasons), it shows
```js
server.log.on('preadd', (action, meta) {
  meta.reasons.push('test')
})
```

Is there a difference between the `server.log.on` method

```js
server.log.on('preadd', // ...
``` 
compared to the `server.log.type` method?

```js
server.log.type('0', () => {
// ...
}, { event: 'preadd' })
```

**Comment by ai** [comment]
> But that doesn't match up with the types in my installed copy. Should this be like this?

Yes. Do you want to send PR?

> Is there a difference between the server.log.on method compared to the server.log.type method?

`log.type` is a little faster option than `log.on`.

If you add callback by `on` it will be fired on every new action. If you add callback by `type`, it will be executed only if `action.type` is matched (with a few optimizations for performance).
